/**
 * QVAC SDK Worker Entry (auto-generated)
 * Generated by: @qvac/sdk/commands bundleSdk
 * Plugins: 2
 *
*   - @qvac/sdk/llamacpp-completion/plugin
*   - @qvac/sdk/whispercpp-transcription/plugin
 */

import { initializeWorker, ensureRPCSetup } from "@qvac/sdk/worker-lifecycle";
import { registerPlugin } from "@qvac/sdk/plugins";
import { getServerLogger } from "@qvac/sdk/logging";

import { llmPlugin } from "@qvac/sdk/llamacpp-completion/plugin";
import { whisperPlugin } from "@qvac/sdk/whispercpp-transcription/plugin";

const { hasRPCConfig } = initializeWorker();

const logger = getServerLogger();
logger.info("🐻 QVAC Worker (custom bundle)");
logger.info("📦 Plugins: 2");

registerPlugin(llmPlugin);
registerPlugin(whisperPlugin);

// Auto-setup RPC if config present
if (hasRPCConfig) {
  ensureRPCSetup();
}
